### ISSUE TITLE
The two-stage fitting procedure is not available when ns == 1

### ISSUE THREAD

**Issue by xiangzhu** [pcarbo/varbvs#10]
I did not notice this detail until I saw this [line](https://github.com/pcarbo/varbvs/blob/master/varbvs-MATLAB/varbvs.m#L677) of `varbvs.m`. 

It seems that when the number of hyperparameter is 1 (`ns == 1`), this two-stage fitting will be ignored automatically, even if one specifies `initialize_params == true`?

**Comment by pcarbo** [comment]
That is correct---initialize_params = true is not useful when there is only one hyperparameter setting (it will have no effect). I've added an error message to varbvs.m to make that more clear.
