### ISSUE TITLE
subroutine missing

### ISSUE THREAD

**Issue by xiangzhu** [pcarbo/varbvs#14]
Hi Peter,

I think one subroutine `computevarlb.m` used in `varbvsmix.m` is missing.

https://github.com/pcarbo/varbvs/blob/master/varbvs-MATLAB/varbvsmix.m#L357 

Repo search result:

https://github.com/pcarbo/varbvs/search?utf8=%E2%9C%93&q=computevarlb&type=

**Comment by pcarbo** [comment]
@xiangzhu The function is defined on line 430 of `varbvsmix.m`. Is it not working for you?

**Comment by xiangzhu** [comment]
I see. Thanks!

I vaguely remember that the lower bound calculation was in a separate M file in previous versions, so I kept searching a file with name `computevarlb.m`.

I will close this issue now.

**Comment by pcarbo** [comment]
@xiangzhu Some terms in the variational lower bound are computed in separate functions, e.g., `int_gamma.m` and `int_klbeta.m`.

**Comment by xiangzhu** [comment]
Yes, I see these files, which seem to be very similar to previous spike-and-slab versions.
