### ISSUE TITLE
Mex flag `-DMATLAB_MEX_FILE`

### ISSUE THREAD

**Issue by xiangzhu** [pcarbo/varbvs#25]
Hi Peter -- I wonder if you could elaborate more on the following sentence in this page: http://pcarbo.github.io/varbvs/varbvs-MATLAB/

> Do not remove flag -DMATLAB_MEX_FILE; this is important for correctly compiling the C code for MATLAB.

It seems that this flag was not used in a previous version of `varbvs` (which I kept a personal copy for previous simulations): https://github.com/xiangzhu/varbvs/blob/master/varbvs-201501/MATLAB/install.m

I am curious about this flag. I could not find any page on this flag in Matlab's documentation site.

FYI, I was able to compile all mex files using this latest `install.m` in Matlab 2017b:

```matlab
$ matlab -nodesktop
MATLAB is selecting SOFTWARE OPENGL rendering.

                                        < M A T L A B (R) >
                              Copyright 1984-2017 The MathWorks, Inc.
                              R2017b (9.3.0.713579) 64-bit (glnxa64)
                                        September 14, 2017


To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.

>> run install.m
Building diagsqmex MEX file.
Building with 'gcc'.
MEX completed successfully.
Building diagsqtmex MEX file.
Building with 'gcc'.
MEX completed successfully.
Building var1mex MEX file.
Building with 'gcc'.
MEX completed successfully.
Building varbvsnormupdatemex MEX file.
Building with 'gcc'.
MEX completed successfully.
Building varbvsbinupdatemex MEX file.
Building with 'gcc'.
MEX completed successfully.
Building varbvsbinzupdatemex MEX file.
Building with 'gcc'.
MEX completed successfully.
Building varbvsmixupdatemex MEX file.
Building with 'gcc'.
MEX completed successfully.
Compilation of MEX files is complete.
```

**Comment by gaow** [comment]
@xiangzhu it seems to be relevant to correct data type mapping to MATLAB -- see [this line](https://github.com/pcarbo/varbvs/blob/022e0da046ece29256a2237a757983bc5902647e/varbvs-R/src/types.h#L17)

**Comment by xiangzhu** [comment]
Hi Gao -- thanks! But I wonder what would be the consequence of removing this flag `-DMATLAB_MEX_FILE`. If I forgot to add this flag, will I get totally wrong results etc?

**Comment by gaow** [comment]
I think without that flag, it should go to [this line](https://github.com/pcarbo/varbvs/blob/022e0da046ece29256a2237a757983bc5902647e/varbvs-R/src/types.h#L26) the `#else` statement, which then configures the R interface type mapping instead. So I guess whether or not it harms depends on whether or not the type mapping actually matter?

**Comment by xiangzhu** [comment]
Thanks @gaow So if I build the C routines for MATLAB **only**, then I can remove everything under the `#else` line, right?

**Comment by pcarbo** [comment]
@xiangzhu Yes, @gaow is correct. This flag is something I defined for my code only. The reason I have `MATLAB_MEX_FILE` is that there are C source files that are used for both MATLAB and the R package. However, the matrices are slightly different when coming from MATLAB and R, so I need to change the code slightly. 

I'm closing this but let me know if you have any other questions about this.

**Comment by xiangzhu** [comment]
@pcarbo  Thanks for the explanation! Now I understand this flag better: it corresponds to `-Dsymbolname` in MEX documentation, and here the `symbolname` is `MATLAB_MEX_FILE`.
