### ISSUE TITLE
Log-odds based on 10

### ISSUE THREAD

**Issue by xiangzhu** [pcarbo/varbvs#26]
https://github.com/pcarbo/varbvs/blob/022e0da046ece29256a2237a757983bc5902647e/varbvs-MATLAB/varbvs.m#L53

Hi Peter -- I wonder whether it would be helpful for new users that you explicitly point out the log-odds   here are based on 10, rather than e, when you first introduce this quantity.

People can definitely figure this out later once they go through the rest of codes, e.g. this line:

https://github.com/pcarbo/varbvs/blob/022e0da046ece29256a2237a757983bc5902647e/varbvs-MATLAB/varbvs.m#L865

**Comment by pcarbo** [comment]
@xiangzhu I think I document this pretty well in `help varbvs`:

> Hyperparameter logodds is the prior log-odds that a variable is included in the regression 
> model; it is defined as `logodds = log10(q/(1-q))`, where q is the prior probability that a 
> variable is included in the regression model. Note that we use the base-10 logarithm instead of 
> the natural logarithm because it is usually more natural to specify prior log-odds settings in 
> this way.

Is there another place I should make this more clear?

**Comment by xiangzhu** [comment]
Yes, your documentation is very clear about the log 10 base. (In general the documentation is very clear everywhere, which makes it quite straightforward to go through and understand the source codes!)

I was wondering whether this log 10 info is available when you first introduce it in the following line (so that readers don't have to go through the paragraph you posted above):

https://github.com/pcarbo/varbvs/blob/022e0da046ece29256a2237a757983bc5902647e/varbvs-MATLAB/varbvs.m#L53

Again, this is really a minor and perhaps unnecessary suggestion. I will let you decide it, and I am closing this issue.
