### ISSUE TITLE
Do you recommend including principal components as covariates to control for population stratification?

### ISSUE THREAD

**Issue by garyzhubc** [pcarbo/varbvs#33]
Do you recommend including principal components as covariates to control for population stratification? Including PCs does account for the latent population structure but can it also dilute the joint association in the case of multi-SNP analysis?

**Comment by pcarbo** [comment]
It depends on what type of population structure you are trying to control for, but, yes, in the past we have successfully used PCs as covariates to control for population structure (e.g., in a GWAS with different European populations).
